apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base/flask-app
  - ./discord-secret.enc.yaml

configMapGenerator:
  - name: flask-app-helm-values
    options:
      disableNameSuffixHash: true
    files:
      - values.yaml=./app_values.yaml

patches:
  # Helm Release namespace (environment)
  - target:
      kind: HelmRelease
      name: flask-app-release
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod
      - op: replace
        path: /spec/targetNamespace
        value: prod
      - op: replace
        path: /spec/chart/spec/sourceRef/namespace
        value: prod
  # Image Repository
  - target:
      kind: ImageRepository
      name: flask-app-image-repo
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod
  # Image Policy
  - target:
      kind: ImagePolicy
      name: flask-app-image-policy
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod
      - op: replace
        path: /spec/imageRepositoryRef/namespace
        value: prod
      - op: replace
        path: /spec/filterTags/pattern
        value: '^v1\.0\.(\d+)$'
  # Image Update Automation
  - target:
      kind: ImageUpdateAutomation
      name: flask-app-image-update-automation
    patch: |-
      - op: replace
        path: /spec/update/path
        value: ./gitops-flux/gitops-configs/apps/prod
      - op: replace
        path: /metadata/namespace
        value: prod
      - op: replace
        path: /spec/git/checkout/ref/branch
        value: main
      - op: replace
        path: /spec/git/push/branch
        value: main
  # Image update automation Alert
  - target:
      kind: Alert
      name: flask-app-image-alert
    patch: |-
      - op: replace
        path: /spec/eventMetadata/Summary
        value: "Image updated for Flask Application deployment"
      - op: replace
        path: /spec/eventMetadata/Cluster
        value: "Prod Cluster"
      - op: replace
        path: /metadata/namespace
        value: prod
  # Helm Status Alert
  - target:
      kind: Alert
      name: flask-app-helm-alert
    patch: |-
      - op: replace
        path: /spec/eventMetadata/Summary
        value: "Helm status for Flask Application deployment"
      - op: replace
        path: /spec/eventMetadata/Cluster
        value: "Prod Cluster"
      - op: replace
        path: /metadata/namespace
        value: prod
  # SOPS Secret
  - target:
      name: app-sops-secret
      kind: Secret
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod