apiVersion: v1
stringData:
    access-key: ENC[AES256_GCM,data:Kq8o7Lt+/oMXqmskNrnUZv8=,iv:pEw82ECDIx4jBeH9Y2u6cigf85twzetM6zNI+Nq5oVM=,tag:JgmUmgjYghTO81vu9cLtNg==,type:str]
    secret-access-key: ENC[AES256_GCM,data:Q52gHVxUaecuz8M06GzO60QtkpCfoEX8edVrHsFXEn5SYcWEnA==,iv:Y8e9W0IoENP+1U7TsyQPAyYQdGiqeOrzI1zkhPmmyMs=,tag:VRl9tIcMhfrTwS7oHwN1bg==,type:str]
kind: Secret
metadata:
    name: awssm-secret
    namespace: default
type: Opaque
sops:
    age:
        - recipient: age13lt3hfptsl6j4scfjra3gcc0pyulgle00wvq8hf87rg8h54cdc9qfu7tm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByc1NQTEg1ZjdZZ2hCZGxl
            NUdEbjg1RjJTeUt1TitZVTIxRmkrVUVsWEZVCmh2UWt2MDJ3QThzeURsSEZnZE45
            TTAxQms3cEUvZkhGL2NXV1FLSlo1ZHMKLS0tIEIwa0p6bW1HYSs3cldqU1Z0U0Qy
            UnVuUXZYTUV2ZUs1eGZaWWg5V3NWNDQKTeGOZPtHdHY0hPkSDNBaIPEBii+M60Gl
            Z/DbNcmsBz1XvRYuERsn2cPHA3DvaFiF0KrVQ1Gssagg8dXnlHK1UQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-06T12:20:59Z"
    mac: ENC[AES256_GCM,data:MNUWRDdRhI68N6Ht2px3/jXQZ3MzCS8/9ywKqoCOSTexi8SkoCM5vyYoQNLerV8G0RG2O9ieHSCylQTCMpwpbugSQFZl5qXyNGYDp0iPSrY6Abw7Bc1FY2zrn1ThG4dzO0shLAu4ixxCogYOzuriWspV0V7g9NpFYO+O2g/HOBs=,iv:jnm8hxYycAeKlvdqZvA/Qoc3I374FC0QH0M+gFMeRwQ=,tag:COpOY1MzQxaSoW7RPmWhfg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
