apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets-release
  namespace: external-secrets
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: external-secrets
  install:
    timeout: 10m
    remediation:
      retries: 3
  upgrade:
    timeout: 10m
    remediation:
      retries: 3
  interval: 2m
  chart:
    spec:
      chart: external-secrets
      version: 0.15.1
      sourceRef:
        kind: HelmRepository
        name: external-secret-repo
        namespace: external-secrets
  targetNamespace: external-secrets