apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-components
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./gitops-flux/gitops-configs/infra
  prune: false
  wait: true
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age