{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flask-app-secret
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend # Name of your SecretStore
    kind: ClusterSecretStore
  target:
    name: flask-app-secret # Name of the Kubernetes secret
    creationPolicy: OwnerReference
  data:
    - secretKey: app-secret
      remoteRef:
        key: {{ .Values.externalSecret.vault.path }}
        property: {{ .Values.externalSecret.vault.key }}
{{- end }}