apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5005
      protocol: TCP
  selector:
    app: flask-app