apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  # Helm Repos
  - ./helm_repo.yaml
  # Secrets (if private container registries are used)
  # - ./dckr_regcred.enc.yaml