apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: discord-webhook
    namespace: dev
stringData:
    address: ENC[AES256_GCM,data:Cuwq5KI2nMeJ0DyvlBf6EHnWXBwtvvuDQsZ9BTioo/m45ibQXWyOFRxtqNRYLz5soutCmOjpm2womoigsHpJSsBfLT+Kg/yVo6F7PYE7OGexcCAbnt38U4fYpXHkGWoL0GlCaK5eitsE7jUjmWlg0WTzuotQ1NDIXg==,iv:fzRd2b3yks5vKW+mrck/fRjDnPSWs70hzFm6ttnq1mY=,tag:kOZpQeuWjIM8fxqcVwx+9g==,type:str]
sops:
    age:
        - recipient: age13lt3hfptsl6j4scfjra3gcc0pyulgle00wvq8hf87rg8h54cdc9qfu7tm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRHc5ZFNFVlp2VEVxZng5
            MTV5RVdwcCtoV0l4WDNreTByNXoxVEIrb0drCk03bjRnQVlMTmlzRVcwVVV4ZmZ4
            eHdWT2orekZwOFl6ZGlmczVFUWFBRTQKLS0tIDluR1piRUJER3BiL0J6aDRTYnBJ
            azVBUGhlL3dvNzR2UU9CU0xqV0IyVmMKH6JerZqxMSS+YI4bN+oS2S1JNRVyBZd4
            /QtEA67OtAQlfgvVgegI6yInzq5/t7FrYNzQgm4A80DUKJm/zDh0qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-07T23:04:47Z"
    mac: ENC[AES256_GCM,data:wYc/SZsksQBxkK0sZCZMuW53q9dsVVbhr9R4FRtMm9AD1HcXX9zQs88o1ruskWfA4saYWkPaQxtXb/eEGj/pf64r1Q5n6Fk6+saBc36UrEl8Jui964GMuOLqwfoHOGznfF2qCu4frtgNeDLs75BxQbZEd995K1CBPSTBrHuDau0=,iv:4PteQEQBrXIFmlPOMkvCQIzj4/gQDEPqk8lL6bDPmj0=,tag:rP4Y6ov81pwXnHxfE0pILg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
