replicaCount: 2

image:
  repository: your-dockerhub-repo/flask-app
  tag: dev-v1.0.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: false
  className: "nginx"
  host: flask-app.example.com

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

externalSecret:
  enabled: true
  vault:
    role: "flask-app-role"
    path: "secret/data/flask-app"
    key: "app-secret"

secret:
  appSecret: "default-app-secret"