apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flask-app-release
  namespace: REPLACE_THIS
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: flask-app
  install:
    timeout: 10m
    remediation:
      retries: 3
  upgrade:
    timeout: 10m
    remediation:
      retries: 3
  interval: 2m
  chart:
    spec:
      chart: flask-app
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: helm-repo
        namespace: REPLACE_THIS
  targetNamespace: REPLACE_THIS
  valuesFrom:
    - kind: ConfigMap
      name: flask-app-helm-values